CREATE TABLE LOGIN 
(
ID_USU	VARCHAR(30) PRIMARY KEY,
SENHA	INT(6)
);

INSERT INTO LOGIN
VALUES
('RODRIGO', 1010);

CREATE TABLE CADASTRO
(
CPF		    BIGINT  PRIMARY KEY,
ID_USU	    VARCHAR(30),
SENHA	    INT(6),
NOME	    VARCHAR(50), 
EMAIL	    VARCHAR(50),
TELEFONE	VARCHAR(20),
CONSTRAINT CADASTRO_ID_USU_FK FOREIGN KEY (ID_USU) REFERENCES LOGIN(ID_USU)
);

INSERT INTO CADASTRO
VALUES
(10203040506, 'YURI', 0909, 'YURI', 'Yuri.Silva09@gmail.com', '91324-5768');

CREATE TABLE ENDERECO
(
CEP		VARCHAR(15) PRIMARY KEY,
CIDADE	VARCHAR(50),
BAIRRO	VARCHAR(30),
NUMERO	INT(6)
);

INSERT INTO ENDERECO
VALUES
('01009-009', 'SAO PAULO', 'ALPHAVILLE', 9090);

CREATE TABLE DEPARTAMENTOS
(
ID_DEPART	INT(5) PRIMARY KEY,
NOME_DEPT 	VARCHAR(30)
);

INSERT INTO DEPARTAMENTOS
VALUES
(010, 'SMARTHPHONE');

INSERT INTO DEPARTAMENTOS
VALUES
(020, 'TV E VIDEO');

INSERT INTO DEPARTAMENTOS
VALUES
(030, 'INFORMATICA');


CREATE TABLE PRODUTOS (
    ID_PRODUTO INT(5) PRIMARY KEY,
    `NOME` VARCHAR(50),
    TIPO VARCHAR(30),
    PRECO DECIMAL(7,2)
);


INSERT INTO PRODUTOS
VALUES
(1, 'IPHONE 14', 'SMARTHPHONE', 5999,99);

INSERT INTO PRODUTOS
VALUES
(2, 'LG OLED55', 'SMART_TV', 4999,99);


CREATE TABLE COMPRA (
    ID_PEDIDO INT(5) PRIMARY KEY,
    ID_PRODUTO INT(5),
    `PRECO` DECIMAL(7,2),
    FRETE VARCHAR(8),
    CUPOM CHAR(10),
    PAGAMENTO CHAR(8),
    PIX CHAR(3),
    CARTAO CHAR(3),
    N_PARCELAS CHAR(2),
    CONSTRAINT COMPRA_ID_PRODUTO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);


INSERT INTO COMPRA
VALUES
(050, 1001, 2000,00, 'GRATIS', 'PROMO10', 'CARTAO', 'NAO', 'SIM', '03');


CREATE TABLE MEUS_PEDIDOS (
    NF VARCHAR(50) PRIMARY KEY,
    ID_PEDIDO INT(5),
    `AGUAR_PAG` CHAR(3),
    DT_PEDIDO DATE,
    COD_RAST VARCHAR(20),
    ENTREGUE CHAR(3),
    CANCEL CHAR(3),
    TRANSP CHAR(3),
    FOREIGN KEY (ID_PEDIDO) REFERENCES COMPRA(ID_PEDIDO)
);

INSERT INTO MEUS_PEDIDOS
VALUES
('NF12345', 050, 'NAO', TO_DATE('2024-01-01', 'YYYY-MM-DD'), 'RA142358BR', 'SIM', 'NAO', 'NAO');
